#!/usr/bin/env sh
# fulfran-dots bootstrap TUI
# Scaffolds a private home-manager flake from the fulfran-dots template.
#
# Steps:
#   1. If no flake.nix in cwd, run nix flake init from template
#   2. Prompt for preset (minimal / full / dev-only / terminal-only)
#   3. Prompt for hostname (sanitized) and username, write hosts/<host>.nix
#   4. Patch flake.nix homeConfigurations, offer home-manager switch

set -eu

FULFRAN_FLAKE_URL="${FULFRAN_FLAKE_URL:-github:FullFran/fulfran-dots}"

# ── 0. Helper detection ────────────────────────────────────────────────────

have() { command -v "$1" >/dev/null 2>&1; }

# POSIX-portable in-place sed (GNU vs BSD compat).
_sed_inplace() {
  if sed --version >/dev/null 2>&1; then
    # GNU sed
    sed -i "$@"
  else
    # BSD sed (macOS)
    sed -i '' "$@"
  fi
}

ui_select() {
  # ui_select <prompt> <opt1> <opt2> ...
  prompt="$1"; shift
  if have gum; then
    printf '%s\n' "$@" | gum choose --header="$prompt"
  elif have whiptail; then
    args=""
    for o in "$@"; do args="$args $o $o"; done
    # shellcheck disable=SC2086
    whiptail --title "fulfran-dots" --menu "$prompt" 20 60 12 $args 3>&1 1>&2 2>&3
  else
    printf '%s\n' "$prompt" >&2
    i=1
    for o in "$@"; do
      printf '  %d) %s\n' "$i" "$o" >&2
      i=$((i + 1))
    done
    printf 'choice (number): ' >&2
    read -r c
    i=1
    for o in "$@"; do
      if [ "$i" = "$c" ]; then printf '%s' "$o"; return; fi
      i=$((i + 1))
    done
    printf '%s' "$1"  # default to first option
  fi
}

ui_input() {
  # ui_input <prompt> <default>
  prompt="$1"; def="${2:-}"
  if have gum; then
    gum input --prompt "$prompt: " --value "$def"
  elif have whiptail; then
    whiptail --title "fulfran-dots" --inputbox "$prompt" 10 60 "$def" 3>&1 1>&2 2>&3
  else
    printf '%s [%s]: ' "$prompt" "$def" >&2
    read -r v
    printf '%s' "${v:-$def}"
  fi
}

ui_confirm() {
  # ui_confirm <prompt>  -- returns 0 for yes, 1 for no
  prompt="$1"
  if have gum; then
    gum confirm "$prompt"
  elif have whiptail; then
    whiptail --yesno "$prompt" 10 60
  else
    printf '%s [y/N]: ' "$prompt" >&2
    read -r r
    case "$r" in
      y|Y) return 0 ;;
      *)   return 1 ;;
    esac
  fi
}

# ── 1. Prerequisites ────────────────────────────────────────────────────────

have nix || { printf 'nix not found. Install via https://install.determinate.systems\n' >&2; exit 1; }

# ── 2. Detect current platform ──────────────────────────────────────────────

_detect_nix_system() {
  uname_s=$(uname -s)
  uname_m=$(uname -m)
  case "$uname_s" in
    Darwin)
      case "$uname_m" in
        arm64) printf 'aarch64-darwin' ;;
        *)     printf 'x86_64-darwin'  ;;
      esac
      ;;
    *)
      case "$uname_m" in
        aarch64|arm64) printf 'aarch64-linux' ;;
        *)             printf 'x86_64-linux'  ;;
      esac
      ;;
  esac
}

_detect_home_dir() {
  # Returns the platform-appropriate home directory path for a given user.
  # $1 = username
  uname_s=$(uname -s)
  case "$uname_s" in
    Darwin) printf '/Users/%s' "$1" ;;
    *)      printf '/home/%s'  "$1" ;;
  esac
}

nix_system=$(_detect_nix_system)

# ── 3. Scaffold if no flake.nix ─────────────────────────────────────────────

if [ ! -f flake.nix ]; then
  printf 'No flake.nix in cwd — initializing from template...\n' >&2
  nix flake init -t "$FULFRAN_FLAKE_URL"
else
  printf 'flake.nix already exists — skipping template init.\n' >&2
fi

# ── 4. Preset selection ─────────────────────────────────────────────────────

preset=$(ui_select "Pick a preset" minimal full dev-only terminal-only)
preset="${preset:-full}"

# ── 5. Hostname + sanitization ──────────────────────────────────────────────

raw_host=$(ui_input "Hostname" "$(uname -n 2>/dev/null || printf 'my-host')")
host=$(printf '%s' "$raw_host" \
  | tr '[:upper:] ' '[:lower:]-' \
  | sed -E 's/[^a-z0-9-]+/-/g; s/-+/-/g; s/^-//; s/-$//')

[ -n "$host" ] || { printf 'Invalid hostname after sanitization.\n' >&2; exit 1; }

# ── 6. Username ─────────────────────────────────────────────────────────────

user=$(ui_input "Username" "${USER:-user}")
[ -n "$user" ] || { printf 'Username cannot be empty.\n' >&2; exit 1; }

home_dir=$(_detect_home_dir "$user")

# ── 7. Write hosts/<host>.nix ───────────────────────────────────────────────

mkdir -p hosts
cat > "hosts/${host}.nix" <<EOF
# Generated by fulfran-dots TUI on $(date -Iseconds 2>/dev/null || date)
{ pkgs, lib, ... }:
{
  home.username = "${user}";
  home.homeDirectory =
    if pkgs.stdenv.isDarwin
    then "/Users/${user}"
    else "/home/${user}";

  home.stateVersion = "25.05";

  # Override fulfran-dots toggles below. All defaults are true unless noted.
  # programs.fulfran.tmux.enableConfig = false;       # keep your tmux.conf
  # programs.fulfran.ghostty.enableConfig = false;    # keep your ghostty config
  # programs.fulfran.nvim.enableConfig = false;       # keep your nvim
  # programs.fulfran.shell.enableBash = false;        # keep your .bashrc
  # programs.fulfran.shell.enableZsh = false;         # keep your .zshrc
  # programs.fulfran.lazygit.enableConfig = false;    # keep your lazygit
  # programs.fulfran.dev.enableJdk = true;            # opt-in to jdk21
}
EOF

printf 'Wrote hosts/%s.nix\n' "$host" >&2

# ── 8. Patch flake.nix at the marker ────────────────────────────────────────

if [ ! -f flake.nix ]; then
  printf 'flake.nix not found — cannot patch.\n' >&2
  exit 1
fi

if ! grep -q '# FULFRAN_TUI_INSERT_HERE' flake.nix; then
  printf 'Warning: marker # FULFRAN_TUI_INSERT_HERE not found in flake.nix.\n' >&2
  printf 'Add the entry for "%s@%s" manually.\n' "$user" "$host" >&2
else
  # Try Python3 first for clean string substitution, fall back to sed
  _patch_with_python() {
    python3 - "$1" "$2" "$3" "$4" <<'PY'
import sys, pathlib
u, h, preset, nix_system = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4]
p = pathlib.Path("flake.nix")
src = p.read_text()
entry = (
    f'        "{u}@{h}" = home-manager.lib.homeManagerConfiguration {{\n'
    f'          pkgs = pkgsFor "{nix_system}";\n'
    f'          modules = [ fulfran-dots.homeManagerModules.{preset} ./hosts/{h}.nix ];\n'
    f'        }};\n'
    f'        # FULFRAN_TUI_INSERT_HERE'
)
new = src.replace("# FULFRAN_TUI_INSERT_HERE", entry)
p.write_text(new)
PY
  }

  _patch_with_sed() {
    # sed fallback — BSD and GNU compatible via _sed_inplace
    _sed_inplace "s|# FULFRAN_TUI_INSERT_HERE|        \"${user}@${host}\" = home-manager.lib.homeManagerConfiguration {\n          pkgs = pkgsFor \"${nix_system}\";\n          modules = [ fulfran-dots.homeManagerModules.${preset} .\/hosts\/${host}.nix ];\n        };\n        # FULFRAN_TUI_INSERT_HERE|" flake.nix
  }

  if have python3; then
    _patch_with_python "$user" "$host" "$preset" "$nix_system" || _patch_with_sed
  else
    _patch_with_sed
  fi
  printf 'Registered %s@%s in flake.nix\n' "$user" "$host" >&2
fi

# ── 9. Optional home-manager switch ─────────────────────────────────────────

if ui_confirm "Run home-manager switch --flake .#${user}@${host} -b backup now?"; then
  nix run nixpkgs#home-manager -- switch --flake ".#${user}@${host}" -b backup
fi

printf 'Done. Edit hosts/%s.nix to customize.\n' "$host" >&2
